#!/bin/sh

post_install() {
  echo ""
  echo "This hook will look for AUR packages that requires rebuild to keep working due to ABI changes in shared libraries."
  echo ""
  echo "You can change the behaviour editing the following file"
  echo "    /usr/share/aur-check-rebuild/settings.json"
  echo ""

  if [ ! -f "/usr/share/aur-check-rebuild/database.db" ]; then
      /usr/share/libalpm/scripts/aur-check-rebuild/aur-check-rebuild.py --database
  fi
}
post_upgrade() {
  post_install
}

post_remove() {
  rm -f /usr/share/aur-check-rebuild/database.db
}